In [1]:
import numpy as np
dtype=[('x',np.float64),('y',np.int32)]
s=np.array([(1.5,6),(np.pi,2)],dtype=dtype)
s

array([(1.5       , 6), (3.14159265, 2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [2]:
s[0]

(1.5, 6)

In [3]:
s[1]

(3.14159265, 2)

In [4]:
s[0][1]

6

In [5]:
s[1][0]

3.141592653589793

In [6]:
s['x']

array([1.5       , 3.14159265])

In [7]:
s['y']

array([6, 2])

In [8]:
s['x'][1]

3.141592653589793

In [9]:
s['y'][1]

2

### Pandas

In [11]:
import numpy as np
import pandas as pd

In [12]:
data=np.array(['r','a','n','g','a'])
data

array(['r', 'a', 'n', 'g', 'a'], dtype='<U1')

In [16]:
h=pd.Series(data,[1,2,3,4,5])
h

1    r
2    a
3    n
4    g
5    a
dtype: object

In [18]:
d={1:"Ra",2:"nga",3:"Siva",4:"na"}

In [19]:
d

{1: 'Ra', 2: 'nga', 3: 'Siva', 4: 'na'}

In [21]:
s=pd.Series(d)
s

1      Ra
2     nga
3    Siva
4      na
dtype: object

In [22]:
s[2]

'nga'

In [24]:
s[3]

'Siva'

In [27]:
p=pd.DataFrame([1,2,3,4])
p

0
0  1
1  2
2  3
3  4

In [31]:
k=[[10,"Siva"],[11,"Ranga"],[12,"Rangu"]]
k

[[10, 'Siva'], [11, 'Ranga'], [12, 'Rangu']]

In [37]:
p=pd.DataFrame(k,columns=["Age","Name"])
p

Age   Name
0   10   Siva
1   11  Ranga
2   12  Rangu

In [38]:
p.index

RangeIndex(start=0, stop=3, step=1)

In [39]:
p.values

array([[10, 'Siva'],
       [11, 'Ranga'],
       [12, 'Rangu']], dtype=object)

In [40]:
p.columns

Index(['Age', 'Name'], dtype='object')

In [45]:
p.isnull()

Age   Name
0  False  False
1  False  False
2  False  False

In [47]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.ones_like([5,5])

array([1, 1])

In [49]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [51]:
np.zeros_like([5,2])

array([0, 0])

In [56]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [58]:
np.zeros_like(6)

array(0)

In [67]:
np.random.randint(1,6,5)

array([5, 1, 5, 2, 1])

## Numpy

In [68]:
import numpy as np

In [70]:
np.array([1,5,9,7])

array([1, 5, 9, 7])

In [71]:
d=["siva","ranga","nayak","rangu"]
np.array(d)

array(['siva', 'ranga', 'nayak', 'rangu'], dtype='<U5')

In [72]:
np.size(d)

4

In [74]:
p=np.array([[1,2,3],[4,5,6],[7,8,9]])
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
p[0]

array([1, 2, 3])

In [76]:
p[0][0]

1

In [77]:
p[0][2]

3

In [78]:
p[1]

array([4, 5, 6])

In [79]:
p[2]

array([7, 8, 9])

In [80]:
p[1][2]

6

In [93]:
k=np.arange(24).reshape(4,3,2)
h=np.array(k)
h

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [94]:
h[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
h[1]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [96]:
h[2]

array([[12, 13],
       [14, 15],
       [16, 17]])

In [97]:
h[0][0]

array([0, 1])

In [98]:
h[0][0][0]

0

In [101]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
p.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
np.sin(90)

0.8939966636005579

In [111]:
np.cos(0)

1.0

In [112]:
np.tan(45)

1.6197751905438615

In [116]:
np.linalg.inv(p)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [117]:
np.linalg.det(p)

-9.51619735392994e-16

In [118]:
np.diag(p)

array([1, 5, 9])

In [120]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [121]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [123]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [124]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [126]:
np.linalg.eig(p)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))